import type { Metadata } from "next";

import "../globals.css";
import Header from "@/components/Header";
import { AppProviders } from "@/context/AppProviders";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppProviders>
      <div>
        <Header />
        {children}
      </div>
    </AppProviders>
  );
}
