// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/analytics" | "/admin/interests" | "/admin/moderation" | "/admin/packages" | "/admin/revenue" | "/admin/subscriptions" | "/admin/users" | "/admin/verification" | "/compatibility" | "/dashboard" | "/dashboard/compatibility" | "/dashboard/featured" | "/dashboard/interests/received" | "/dashboard/interests/sent" | "/dashboard/matches" | "/dashboard/messages" | "/dashboard/packages" | "/dashboard/profile" | "/dashboard/profile/visitors" | "/dashboard/search" | "/dashboard/search/advanced" | "/dashboard/settings" | "/dashboard/settings/account" | "/dashboard/settings/notifications" | "/dashboard/settings/privacy" | "/dashboard/vip" | "/dashboard/vip/dashboard" | "/dashboard/vip/handpicked-matches" | "/dashboard/vip/matchmaker" | "/featured" | "/interests/received" | "/interests/sent" | "/login" | "/matches" | "/messages" | "/packages" | "/profile" | "/profile/[id]" | "/profile/visitors" | "/realtime-test" | "/register" | "/search" | "/search/advanced" | "/test-messaging" | "/vip/dashboard"
type AppRouteHandlerRoutes = "/api/admin/create" | "/api/admin/stats" | "/api/admin/users" | "/api/admin/users-paginate" | "/api/admin/users/[id]" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/register" | "/api/business/features" | "/api/chat/messages" | "/api/chat/rooms" | "/api/compatibility/analyze" | "/api/conversations" | "/api/debug/subscription" | "/api/featured" | "/api/interests" | "/api/interests/enhanced" | "/api/matches" | "/api/me" | "/api/messages" | "/api/packages" | "/api/packages/[id]" | "/api/profile" | "/api/profile-visits" | "/api/profile/preferences" | "/api/profiles" | "/api/search" | "/api/search/enhanced" | "/api/seed/packages" | "/api/simple-messages" | "/api/subscriptions" | "/api/upload" | "/api/users" | "/api/users/[id]" | "/api/vip/events" | "/api/vip/handpicked-matches" | "/api/vip/services"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/analytics": {}
  "/admin/interests": {}
  "/admin/moderation": {}
  "/admin/packages": {}
  "/admin/revenue": {}
  "/admin/subscriptions": {}
  "/admin/users": {}
  "/admin/verification": {}
  "/api/admin/create": {}
  "/api/admin/stats": {}
  "/api/admin/users": {}
  "/api/admin/users-paginate": {}
  "/api/admin/users/[id]": { "id": string; }
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/register": {}
  "/api/business/features": {}
  "/api/chat/messages": {}
  "/api/chat/rooms": {}
  "/api/compatibility/analyze": {}
  "/api/conversations": {}
  "/api/debug/subscription": {}
  "/api/featured": {}
  "/api/interests": {}
  "/api/interests/enhanced": {}
  "/api/matches": {}
  "/api/me": {}
  "/api/messages": {}
  "/api/packages": {}
  "/api/packages/[id]": { "id": string; }
  "/api/profile": {}
  "/api/profile-visits": {}
  "/api/profile/preferences": {}
  "/api/profiles": {}
  "/api/search": {}
  "/api/search/enhanced": {}
  "/api/seed/packages": {}
  "/api/simple-messages": {}
  "/api/subscriptions": {}
  "/api/upload": {}
  "/api/users": {}
  "/api/users/[id]": { "id": string; }
  "/api/vip/events": {}
  "/api/vip/handpicked-matches": {}
  "/api/vip/services": {}
  "/compatibility": {}
  "/dashboard": {}
  "/dashboard/compatibility": {}
  "/dashboard/featured": {}
  "/dashboard/interests/received": {}
  "/dashboard/interests/sent": {}
  "/dashboard/matches": {}
  "/dashboard/messages": {}
  "/dashboard/packages": {}
  "/dashboard/profile": {}
  "/dashboard/profile/visitors": {}
  "/dashboard/search": {}
  "/dashboard/search/advanced": {}
  "/dashboard/settings": {}
  "/dashboard/settings/account": {}
  "/dashboard/settings/notifications": {}
  "/dashboard/settings/privacy": {}
  "/dashboard/vip": {}
  "/dashboard/vip/dashboard": {}
  "/dashboard/vip/handpicked-matches": {}
  "/dashboard/vip/matchmaker": {}
  "/featured": {}
  "/interests/received": {}
  "/interests/sent": {}
  "/login": {}
  "/matches": {}
  "/messages": {}
  "/packages": {}
  "/profile": {}
  "/profile/[id]": { "id": string; }
  "/profile/visitors": {}
  "/realtime-test": {}
  "/register": {}
  "/search": {}
  "/search/advanced": {}
  "/test-messaging": {}
  "/vip/dashboard": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
