// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/dist/lib/metadata/types/metadata-interface.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response> | Response | Promise<void> | void
}

type ApiRouteConfig = {
  default: (req: any, res: any) => Promise<void> | void | Promise<Response> | Response
  config?: {
    api?: {
      bodyParser?: boolean | { sizeLimit?: string }
      responseLimit?: string | number
      externalResolver?: boolean
    }
    runtime?: 'edge' | 'experimental-edge' | 'nodejs' | string // necessary unless config is exported as const
    maxDuration?: number
  }
}


// Validate ..\..\src\app\(admin)\admin\analytics\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\admin\\analytics\\page.js")
  handler satisfies AppPageConfig<"/admin/analytics">
}

// Validate ..\..\src\app\(admin)\admin\interests\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\admin\\interests\\page.js")
  handler satisfies AppPageConfig<"/admin/interests">
}

// Validate ..\..\src\app\(admin)\admin\moderation\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\admin\\moderation\\page.js")
  handler satisfies AppPageConfig<"/admin/moderation">
}

// Validate ..\..\src\app\(admin)\admin\packages\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\admin\\packages\\page.js")
  handler satisfies AppPageConfig<"/admin/packages">
}

// Validate ..\..\src\app\(admin)\admin\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\admin\\page.js")
  handler satisfies AppPageConfig<"/admin">
}

// Validate ..\..\src\app\(admin)\admin\revenue\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\admin\\revenue\\page.js")
  handler satisfies AppPageConfig<"/admin/revenue">
}

// Validate ..\..\src\app\(admin)\admin\subscriptions\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\admin\\subscriptions\\page.js")
  handler satisfies AppPageConfig<"/admin/subscriptions">
}

// Validate ..\..\src\app\(admin)\admin\users\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\admin\\users\\page.js")
  handler satisfies AppPageConfig<"/admin/users">
}

// Validate ..\..\src\app\(admin)\admin\verification\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\admin\\verification\\page.js")
  handler satisfies AppPageConfig<"/admin/verification">
}

// Validate ..\..\src\app\(admin)\dashboard\compatibility\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\dashboard\\compatibility\\page.js")
  handler satisfies AppPageConfig<"/dashboard/compatibility">
}

// Validate ..\..\src\app\(admin)\dashboard\featured\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\dashboard\\featured\\page.js")
  handler satisfies AppPageConfig<"/dashboard/featured">
}

// Validate ..\..\src\app\(admin)\dashboard\interests\received\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\dashboard\\interests\\received\\page.js")
  handler satisfies AppPageConfig<"/dashboard/interests/received">
}

// Validate ..\..\src\app\(admin)\dashboard\interests\sent\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\dashboard\\interests\\sent\\page.js")
  handler satisfies AppPageConfig<"/dashboard/interests/sent">
}

// Validate ..\..\src\app\(admin)\dashboard\matches\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\dashboard\\matches\\page.js")
  handler satisfies AppPageConfig<"/dashboard/matches">
}

// Validate ..\..\src\app\(admin)\dashboard\messages\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\dashboard\\messages\\page.js")
  handler satisfies AppPageConfig<"/dashboard/messages">
}

// Validate ..\..\src\app\(admin)\dashboard\packages\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\dashboard\\packages\\page.js")
  handler satisfies AppPageConfig<"/dashboard/packages">
}

// Validate ..\..\src\app\(admin)\dashboard\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\dashboard\\page.js")
  handler satisfies AppPageConfig<"/dashboard">
}

// Validate ..\..\src\app\(admin)\dashboard\profile\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\dashboard\\profile\\page.js")
  handler satisfies AppPageConfig<"/dashboard/profile">
}

// Validate ..\..\src\app\(admin)\dashboard\profile\visitors\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\dashboard\\profile\\visitors\\page.js")
  handler satisfies AppPageConfig<"/dashboard/profile/visitors">
}

// Validate ..\..\src\app\(admin)\dashboard\search\advanced\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\dashboard\\search\\advanced\\page.js")
  handler satisfies AppPageConfig<"/dashboard/search/advanced">
}

// Validate ..\..\src\app\(admin)\dashboard\search\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\dashboard\\search\\page.js")
  handler satisfies AppPageConfig<"/dashboard/search">
}

// Validate ..\..\src\app\(admin)\dashboard\settings\account\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\dashboard\\settings\\account\\page.js")
  handler satisfies AppPageConfig<"/dashboard/settings/account">
}

// Validate ..\..\src\app\(admin)\dashboard\settings\notifications\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\dashboard\\settings\\notifications\\page.js")
  handler satisfies AppPageConfig<"/dashboard/settings/notifications">
}

// Validate ..\..\src\app\(admin)\dashboard\settings\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\dashboard\\settings\\page.js")
  handler satisfies AppPageConfig<"/dashboard/settings">
}

// Validate ..\..\src\app\(admin)\dashboard\settings\privacy\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\dashboard\\settings\\privacy\\page.js")
  handler satisfies AppPageConfig<"/dashboard/settings/privacy">
}

// Validate ..\..\src\app\(admin)\dashboard\vip\dashboard\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\dashboard\\vip\\dashboard\\page.js")
  handler satisfies AppPageConfig<"/dashboard/vip/dashboard">
}

// Validate ..\..\src\app\(admin)\dashboard\vip\handpicked-matches\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\dashboard\\vip\\handpicked-matches\\page.js")
  handler satisfies AppPageConfig<"/dashboard/vip/handpicked-matches">
}

// Validate ..\..\src\app\(admin)\dashboard\vip\matchmaker\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\dashboard\\vip\\matchmaker\\page.js")
  handler satisfies AppPageConfig<"/dashboard/vip/matchmaker">
}

// Validate ..\..\src\app\(admin)\dashboard\vip\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\dashboard\\vip\\page.js")
  handler satisfies AppPageConfig<"/dashboard/vip">
}

// Validate ..\..\src\app\(auth)\login\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(auth)\\login\\page.js")
  handler satisfies AppPageConfig<"/login">
}

// Validate ..\..\src\app\(auth)\register\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(auth)\\register\\page.js")
  handler satisfies AppPageConfig<"/register">
}

// Validate ..\..\src\app\(main)\compatibility\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(main)\\compatibility\\page.js")
  handler satisfies AppPageConfig<"/compatibility">
}

// Validate ..\..\src\app\(main)\featured\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(main)\\featured\\page.js")
  handler satisfies AppPageConfig<"/featured">
}

// Validate ..\..\src\app\(main)\interests\received\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(main)\\interests\\received\\page.js")
  handler satisfies AppPageConfig<"/interests/received">
}

// Validate ..\..\src\app\(main)\interests\sent\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(main)\\interests\\sent\\page.js")
  handler satisfies AppPageConfig<"/interests/sent">
}

// Validate ..\..\src\app\(main)\matches\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(main)\\matches\\page.js")
  handler satisfies AppPageConfig<"/matches">
}

// Validate ..\..\src\app\(main)\messages\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(main)\\messages\\page.js")
  handler satisfies AppPageConfig<"/messages">
}

// Validate ..\..\src\app\(main)\packages\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(main)\\packages\\page.js")
  handler satisfies AppPageConfig<"/packages">
}

// Validate ..\..\src\app\(main)\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(main)\\page.js")
  handler satisfies AppPageConfig<"/">
}

// Validate ..\..\src\app\(main)\profile\[id]\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(main)\\profile\\[id]\\page.js")
  handler satisfies AppPageConfig<"/profile/[id]">
}

// Validate ..\..\src\app\(main)\profile\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(main)\\profile\\page.js")
  handler satisfies AppPageConfig<"/profile">
}

// Validate ..\..\src\app\(main)\profile\visitors\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(main)\\profile\\visitors\\page.js")
  handler satisfies AppPageConfig<"/profile/visitors">
}

// Validate ..\..\src\app\(main)\search\advanced\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(main)\\search\\advanced\\page.js")
  handler satisfies AppPageConfig<"/search/advanced">
}

// Validate ..\..\src\app\(main)\search\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(main)\\search\\page.js")
  handler satisfies AppPageConfig<"/search">
}

// Validate ..\..\src\app\(main)\test-messaging\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(main)\\test-messaging\\page.js")
  handler satisfies AppPageConfig<"/test-messaging">
}

// Validate ..\..\src\app\(main)\vip\dashboard\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(main)\\vip\\dashboard\\page.js")
  handler satisfies AppPageConfig<"/vip/dashboard">
}

// Validate ..\..\src\app\realtime-test\page.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\realtime-test\\page.js")
  handler satisfies AppPageConfig<"/realtime-test">
}

// Validate ..\..\src\app\api\admin\create\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\admin\\create\\route.js")
  handler satisfies RouteHandlerConfig<"/api/admin/create">
}

// Validate ..\..\src\app\api\admin\stats\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\admin\\stats\\route.js")
  handler satisfies RouteHandlerConfig<"/api/admin/stats">
}

// Validate ..\..\src\app\api\admin\users-paginate\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\admin\\users-paginate\\route.js")
  handler satisfies RouteHandlerConfig<"/api/admin/users-paginate">
}

// Validate ..\..\src\app\api\admin\users\[id]\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\admin\\users\\[id]\\route.js")
  handler satisfies RouteHandlerConfig<"/api/admin/users/[id]">
}

// Validate ..\..\src\app\api\admin\users\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\admin\\users\\route.js")
  handler satisfies RouteHandlerConfig<"/api/admin/users">
}

// Validate ..\..\src\app\api\auth\login\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\auth\\login\\route.js")
  handler satisfies RouteHandlerConfig<"/api/auth/login">
}

// Validate ..\..\src\app\api\auth\logout\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\auth\\logout\\route.js")
  handler satisfies RouteHandlerConfig<"/api/auth/logout">
}

// Validate ..\..\src\app\api\auth\register\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\auth\\register\\route.js")
  handler satisfies RouteHandlerConfig<"/api/auth/register">
}

// Validate ..\..\src\app\api\business\features\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\business\\features\\route.js")
  handler satisfies RouteHandlerConfig<"/api/business/features">
}

// Validate ..\..\src\app\api\chat\messages\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\chat\\messages\\route.js")
  handler satisfies RouteHandlerConfig<"/api/chat/messages">
}

// Validate ..\..\src\app\api\chat\rooms\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\chat\\rooms\\route.js")
  handler satisfies RouteHandlerConfig<"/api/chat/rooms">
}

// Validate ..\..\src\app\api\compatibility\analyze\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\compatibility\\analyze\\route.js")
  handler satisfies RouteHandlerConfig<"/api/compatibility/analyze">
}

// Validate ..\..\src\app\api\conversations\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\conversations\\route.js")
  handler satisfies RouteHandlerConfig<"/api/conversations">
}

// Validate ..\..\src\app\api\debug\subscription\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\debug\\subscription\\route.js")
  handler satisfies RouteHandlerConfig<"/api/debug/subscription">
}

// Validate ..\..\src\app\api\featured\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\featured\\route.js")
  handler satisfies RouteHandlerConfig<"/api/featured">
}

// Validate ..\..\src\app\api\interests\enhanced\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\interests\\enhanced\\route.js")
  handler satisfies RouteHandlerConfig<"/api/interests/enhanced">
}

// Validate ..\..\src\app\api\interests\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\interests\\route.js")
  handler satisfies RouteHandlerConfig<"/api/interests">
}

// Validate ..\..\src\app\api\matches\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\matches\\route.js")
  handler satisfies RouteHandlerConfig<"/api/matches">
}

// Validate ..\..\src\app\api\me\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\me\\route.js")
  handler satisfies RouteHandlerConfig<"/api/me">
}

// Validate ..\..\src\app\api\messages\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\messages\\route.js")
  handler satisfies RouteHandlerConfig<"/api/messages">
}

// Validate ..\..\src\app\api\packages\[id]\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\packages\\[id]\\route.js")
  handler satisfies RouteHandlerConfig<"/api/packages/[id]">
}

// Validate ..\..\src\app\api\packages\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\packages\\route.js")
  handler satisfies RouteHandlerConfig<"/api/packages">
}

// Validate ..\..\src\app\api\profile-visits\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\profile-visits\\route.js")
  handler satisfies RouteHandlerConfig<"/api/profile-visits">
}

// Validate ..\..\src\app\api\profile\preferences\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\profile\\preferences\\route.js")
  handler satisfies RouteHandlerConfig<"/api/profile/preferences">
}

// Validate ..\..\src\app\api\profile\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\profile\\route.js")
  handler satisfies RouteHandlerConfig<"/api/profile">
}

// Validate ..\..\src\app\api\profiles\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\profiles\\route.js")
  handler satisfies RouteHandlerConfig<"/api/profiles">
}

// Validate ..\..\src\app\api\search\enhanced\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\search\\enhanced\\route.js")
  handler satisfies RouteHandlerConfig<"/api/search/enhanced">
}

// Validate ..\..\src\app\api\search\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\search\\route.js")
  handler satisfies RouteHandlerConfig<"/api/search">
}

// Validate ..\..\src\app\api\seed\packages\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\seed\\packages\\route.js")
  handler satisfies RouteHandlerConfig<"/api/seed/packages">
}

// Validate ..\..\src\app\api\simple-messages\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\simple-messages\\route.js")
  handler satisfies RouteHandlerConfig<"/api/simple-messages">
}

// Validate ..\..\src\app\api\subscriptions\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\subscriptions\\route.js")
  handler satisfies RouteHandlerConfig<"/api/subscriptions">
}

// Validate ..\..\src\app\api\upload\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\upload\\route.js")
  handler satisfies RouteHandlerConfig<"/api/upload">
}

// Validate ..\..\src\app\api\users\[id]\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\users\\[id]\\route.js")
  handler satisfies RouteHandlerConfig<"/api/users/[id]">
}

// Validate ..\..\src\app\api\users\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\users\\route.js")
  handler satisfies RouteHandlerConfig<"/api/users">
}

// Validate ..\..\src\app\api\vip\events\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\vip\\events\\route.js")
  handler satisfies RouteHandlerConfig<"/api/vip/events">
}

// Validate ..\..\src\app\api\vip\handpicked-matches\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\vip\\handpicked-matches\\route.js")
  handler satisfies RouteHandlerConfig<"/api/vip/handpicked-matches">
}

// Validate ..\..\src\app\api\vip\services\route.ts
{
  const handler = {} as typeof import("..\\..\\src\\app\\api\\vip\\services\\route.js")
  handler satisfies RouteHandlerConfig<"/api/vip/services">
}



// Validate ..\..\pages\api\socket.ts
{
  const handler = {} as typeof import("..\\..\\pages\\api\\socket.js")
  handler satisfies ApiRouteConfig
}

// Validate ..\..\pages\api\socketio.ts
{
  const handler = {} as typeof import("..\\..\\pages\\api\\socketio.js")
  handler satisfies ApiRouteConfig
}

// Validate ..\..\src\app\(admin)\admin\layout.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\admin\\layout.js")
  handler satisfies LayoutConfig<"/admin">
}

// Validate ..\..\src\app\(admin)\dashboard\layout.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(admin)\\dashboard\\layout.js")
  handler satisfies LayoutConfig<"/dashboard">
}

// Validate ..\..\src\app\(auth)\layout.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(auth)\\layout.js")
  handler satisfies LayoutConfig<"/">
}

// Validate ..\..\src\app\(main)\layout.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\(main)\\layout.js")
  handler satisfies LayoutConfig<"/">
}

// Validate ..\..\src\app\layout.tsx
{
  const handler = {} as typeof import("..\\..\\src\\app\\layout.js")
  handler satisfies LayoutConfig<"/">
}
